spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/payment
    username: postgres
    password: postgres525
  jpa:
    properties:
      hibernate:
        show_sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: validate
  flyway:
    locations: classpath:db/migration

  kafka:
    bootstrap-servers: 176.126.113.189:29092
    producer:
      bootstrap-servers: 176.126.113.189:29092
      key-serializer: org.apache.kafka.common.serialization.LongSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
    template:
      default-topic: "payment-events"

server:
  port: 8080

