spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://postgres:5432/payment_test
    username: postgres
    password: postgres
  jpa:
    properties:
      hibernate:
        show_sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: validate
  flyway:
    locations: classpath:db/migration

server:
  port: 8080